<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<DefineConstants>UNSAFE</DefineConstants>
		<PackageId>RiceTea.unofficial.Microsoft.Automata.SRM</PackageId>
		<Authors>Microsoft, RiceTea (new1271)</Authors>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/new1271/srm</PackageProjectUrl>
		<Description>High-performance .NET regex engine with predictable performance</Description>
		<PackageTags>regular expression regex matching unicode</PackageTags>
		<PackageIcon>icon.png</PackageIcon>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyVersion>2.1.0.0</AssemblyVersion>
		<PackageVersion>2.1.0.0</PackageVersion>
		<SignAssembly>true</SignAssembly>
		<DelaySign>true</DelaySign>
		<KeyFile>../scripts/35MSSharedLib1024.snk</KeyFile>
		<AssemblyOriginatorKeyFile>../scripts/35MSSharedLib1024.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Collections.Immutable" Version="10.0.10" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="PolySharp" Version="1.16.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectCapability Include="CSharp;Managed;ClassDesigner" />
	</ItemGroup>

	<ItemGroup>
		<None Include="icon.png" Pack="true" PackagePath=""/>
	</ItemGroup>
</Project>
